export const ORDER_WRITE_REPOSITORY = Symbol('ORDER_WRITE_REPOSITORY');
export const ORDER_READ_REPOSITORY = Symbol('ORDER_READ_REPOSITORY');
export const PRODUCT_READ_REPOSITORY = Symbol('PRODUCT_READ_REPOSITORY');
export const USER_READ_REPOSITORY = Symbol('USER_READ_REPOSITORY');
export const WEEKLY_ORDER_EXCEPTION_READ_REPOSITORY = Symbol(
  'WEEKLY_ORDER_EXCEPTION_READ_REPOSITORY',
);
